/**
 * Mock data generator specifically for help page interactive examples
 * Generates realistic data for all sections with variety and completeness
 */

import type { 
  TaskWithRecurrence, 
  OccurrenceWithTask, 
  EventWithDetails, 
  DayOfWeek,
  CalendarEvent 
} from "~/types"

// Helper: generate dates relative to today
const today = new Date()
today.setHours(0, 0, 0, 0)

const addDays = (date: Date, days: number): Date => {
  const result = new Date(date)
  result.setDate(result.getDate() + days)
  return result
}

const addHours = (date: Date, hours: number): Date => {
  const result = new Date(date)
  result.setHours(result.getHours() + hours)
  return result
}

// Mock tasks for different scenarios
export const mockHelpTasks: TaskWithRecurrence[] = [
  {
    id: 1,
    ownerId: "demo-user",
    name: "Completar informe trimestral",
    description: "Preparar y entregar el informe de resultados del Q4",
    recurrenceId: null,
    importance: 9,
    isActive: true,
    isFixed: false,
    fixedStartTime: null,
    fixedEndTime: null,
    completedAt: null,
    createdAt: addDays(today, -5),
    updatedAt: null,
    taskType: "Única",
  },
  {
    id: 2,
    ownerId: "demo-user",
    name: "Ejercicio matutino",
    description: "30 minutos de cardio y estiramientos",
    recurrenceId: 1,
    importance: 7,
    isActive: true,
    isFixed: true,
    fixedStartTime: "07:00:00",
    fixedEndTime: "07:30:00",
    completedAt: null,
    createdAt: addDays(today, -30),
    updatedAt: null,
    recurrence: {
      id: 1,
      creationDate: addDays(today, -30),
      interval: 1,
      daysOfWeek: ["Mon", "Wed", "Fri"],
      daysOfMonth: null,
      maxOccurrences: null,
      completedOccurrences: 24,
      lastPeriodStart: addDays(today, -7),
      endDate: null,
    },
    taskType: "Hábito +",
  },
  {
    id: 3,
    ownerId: "demo-user",
    name: "Revisar emails",
    description: "Responder correos pendientes y organizar bandeja de entrada",
    recurrenceId: 2,
    importance: 5,
    isActive: true,
    isFixed: true,
    fixedStartTime: "09:00:00",
    fixedEndTime: "09:30:00",
    completedAt: null,
    createdAt: addDays(today, -60),
    updatedAt: null,
    recurrence: {
      id: 2,
      creationDate: addDays(today, -60),
      interval: 1,
      daysOfWeek: ["Mon", "Tue", "Wed", "Thu", "Fri"],
      daysOfMonth: null,
      maxOccurrences: null,
      completedOccurrences: 45,
      lastPeriodStart: addDays(today, -7),
      endDate: null,
    },
    taskType: "Hábito +",
  },
  {
    id: 4,
    ownerId: "demo-user",
    name: "Reunión de equipo semanal",
    description: "Sincronización con el equipo de desarrollo",
    recurrenceId: 3,
    importance: 8,
    isActive: true,
    isFixed: true,
    fixedStartTime: "15:00:00",
    fixedEndTime: "16:00:00",
    completedAt: null,
    createdAt: addDays(today, -90),
    updatedAt: null,
    recurrence: {
      id: 3,
      creationDate: addDays(today, -90),
      interval: 7,
      daysOfWeek: ["Mon"],
      daysOfMonth: null,
      maxOccurrences: 20,
      completedOccurrences: 12,
      lastPeriodStart: addDays(today, -7),
      endDate: addDays(today, 60),
    },
    taskType: "Recurrente Finita",
  },
  {
    id: 5,
    ownerId: "demo-user",
    name: "Leer 30 minutos",
    description: "Avanzar en el libro de desarrollo personal",
    recurrenceId: 4,
    importance: 6,
    isActive: true,
    isFixed: false,
    fixedStartTime: null,
    fixedEndTime: null,
    completedAt: null,
    createdAt: addDays(today, -20),
    updatedAt: null,
    recurrence: {
      id: 4,
      creationDate: addDays(today, -20),
      interval: 1,
      daysOfWeek: null,
      daysOfMonth: null,
      maxOccurrences: null,
      completedOccurrences: 18,
      lastPeriodStart: today,
      endDate: null,
    },
    taskType: "Hábito",
  },
  {
    id: 6,
    ownerId: "demo-user",
    name: "Preparar presentación cliente",
    description: "Slides para demo del nuevo producto",
    recurrenceId: null,
    importance: 10,
    isActive: true,
    isFixed: false,
    fixedStartTime: null,
    fixedEndTime: null,
    completedAt: null,
    createdAt: addDays(today, -2),
    updatedAt: null,
    taskType: "Única",
  },
]

// Mock occurrences with variety of statuses
export const mockHelpOccurrences: OccurrenceWithTask[] = [
  // Urgent - overdue
  {
    id: 1,
    associatedTaskId: 1,
    startDate: addDays(today, -3),
    limitDate: addDays(today, -1),
    targetDate: addDays(today, -1),
    targetTimeConsumption: 180,
    timeConsumed: 0,
    status: "Pending",
    urgency: 9,
    completedAt: null,
    createdAt: addDays(today, -3),
    updatedAt: null,
    task: mockHelpTasks[0]!,
  },
  // Urgent - today
  {
    id: 2,
    associatedTaskId: 6,
    startDate: addDays(today, -2),
    limitDate: today,
    targetDate: today,
    targetTimeConsumption: 240,
    timeConsumed: 120,
    status: "Pending",
    urgency: 10,
    completedAt: null,
    createdAt: addDays(today, -2),
    updatedAt: null,
    task: mockHelpTasks[5]!,
  },
  // Today - exercise
  {
    id: 3,
    associatedTaskId: 2,
    startDate: today,
    limitDate: null,
    targetDate: today,
    targetTimeConsumption: 30,
    timeConsumed: 0,
    status: "Pending",
    urgency: 7,
    completedAt: null,
    createdAt: today,
    updatedAt: null,
    task: mockHelpTasks[1]!,
  },
  // Today - emails
  {
    id: 4,
    associatedTaskId: 3,
    startDate: today,
    limitDate: null,
    targetDate: today,
    targetTimeConsumption: 30,
    timeConsumed: 30,
    status: "Completed",
    urgency: 5,
    completedAt: addHours(today, 9),
    createdAt: today,
    updatedAt: addHours(today, 9),
    task: mockHelpTasks[2]!,
  },
  // Tomorrow - reading
  {
    id: 5,
    associatedTaskId: 5,
    startDate: addDays(today, 1),
    limitDate: null,
    targetDate: addDays(today, 1),
    targetTimeConsumption: 30,
    timeConsumed: 0,
    status: "Pending",
    urgency: 6,
    completedAt: null,
    createdAt: today,
    updatedAt: null,
    task: mockHelpTasks[4]!,
  },
  // Next week - meeting
  {
    id: 6,
    associatedTaskId: 4,
    startDate: addDays(today, 7),
    limitDate: null,
    targetDate: addDays(today, 7),
    targetTimeConsumption: 60,
    timeConsumed: 0,
    status: "Pending",
    urgency: 8,
    completedAt: null,
    createdAt: today,
    updatedAt: null,
    task: mockHelpTasks[3]!,
  },
  // Completed yesterday
  {
    id: 7,
    associatedTaskId: 2,
    startDate: addDays(today, -1),
    limitDate: null,
    targetDate: addDays(today, -1),
    targetTimeConsumption: 30,
    timeConsumed: 35,
    status: "Completed",
    urgency: 7,
    completedAt: addHours(addDays(today, -1), 7),
    createdAt: addDays(today, -1),
    updatedAt: addHours(addDays(today, -1), 7),
    task: mockHelpTasks[1]!,
  },
  // Skipped
  {
    id: 8,
    associatedTaskId: 5,
    startDate: addDays(today, -2),
    limitDate: null,
    targetDate: addDays(today, -2),
    targetTimeConsumption: 30,
    timeConsumed: 0,
    status: "Skipped",
    urgency: 6,
    completedAt: null,
    createdAt: addDays(today, -2),
    updatedAt: addDays(today, -2),
    task: mockHelpTasks[4]!,
  },
]

// Mock calendar events for calendar view examples
export const mockHelpEvents: EventWithDetails[] = [
  {
    id: 1,
    context: "Sesión de trabajo - Informe",
    ownerId: "demo-user",
    associatedOccurrenceId: 1,
    isFixed: false,
    start: addHours(today, 10),
    finish: addHours(today, 12),
    isCompleted: false,
    dedicatedTime: 120,
    completedAt: null,
    createdAt: today,
    updatedAt: null,
    occurrence: mockHelpOccurrences[0]!,
  },
  {
    id: 2,
    context: "Trabajo en presentación",
    ownerId: "demo-user",
    associatedOccurrenceId: 2,
    isFixed: false,
    start: addHours(today, 14),
    finish: addHours(today, 16),
    isCompleted: false,
    dedicatedTime: 120,
    completedAt: null,
    createdAt: today,
    updatedAt: null,
    occurrence: mockHelpOccurrences[1]!,
  },
  {
    id: 3,
    context: "Ejercicio matutino",
    ownerId: "demo-user",
    associatedOccurrenceId: 3,
    isFixed: true,
    start: addHours(today, 7),
    finish: addHours(addDays(today, 0), 7.5),
    isCompleted: false,
    dedicatedTime: 30,
    completedAt: null,
    createdAt: today,
    updatedAt: null,
    occurrence: mockHelpOccurrences[2]!,
  },
  {
    id: 4,
    context: "Revisar emails",
    ownerId: "demo-user",
    associatedOccurrenceId: 4,
    isFixed: true,
    start: addHours(today, 9),
    finish: addHours(addDays(today, 0), 9.5),
    isCompleted: true,
    dedicatedTime: 30,
    completedAt: addHours(today, 9.5),
    createdAt: today,
    updatedAt: addHours(today, 9.5),
    occurrence: mockHelpOccurrences[3]!,
  },
  // Tomorrow events
  {
    id: 5,
    context: "Lectura diaria",
    ownerId: "demo-user",
    associatedOccurrenceId: 5,
    isFixed: false,
    start: addHours(addDays(today, 1), 20),
    finish: addHours(addDays(today, 1), 20.5),
    isCompleted: false,
    dedicatedTime: 30,
    completedAt: null,
    createdAt: today,
    updatedAt: null,
    occurrence: mockHelpOccurrences[4]!,
  },
  // Next week
  {
    id: 6,
    context: "Reunión de equipo semanal",
    ownerId: "demo-user",
    associatedOccurrenceId: 6,
    isFixed: true,
    start: addHours(addDays(today, 7), 15),
    finish: addHours(addDays(today, 7), 16),
    isCompleted: false,
    dedicatedTime: 60,
    completedAt: null,
    createdAt: today,
    updatedAt: null,
    occurrence: mockHelpOccurrences[5]!,
  },
]

// Mock statistics data
export const mockHelpStats = {
  totalTasks: mockHelpTasks.length,
  activeTasks: mockHelpTasks.filter(t => t.isActive).length,
  completedTasks: mockHelpTasks.filter(t => t.completedAt).length,
  totalOccurrences: mockHelpOccurrences.length,
  completedOccurrences: mockHelpOccurrences.filter(o => o.status === "Completed").length,
  skippedOccurrences: mockHelpOccurrences.filter(o => o.status === "Skipped").length,
  pendingOccurrences: mockHelpOccurrences.filter(o => o.status === "Pending").length,
  totalTimeSpent: mockHelpOccurrences.reduce((sum, o) => sum + (o.timeConsumed ?? 0), 0),
  averageCompletionTime: 35,
  completionRate: 0.72,
}
