CREATE TABLE "flex-calendar_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "flex-calendar_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "flex-calendar_calendar_event" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flex-calendar_calendar_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"context" text,
	"ownerId" varchar(255) NOT NULL,
	"associatedOccurrenceId" integer,
	"isFixed" boolean DEFAULT false NOT NULL,
	"start" timestamp with time zone NOT NULL,
	"finish" timestamp with time zone NOT NULL,
	"isCompleted" boolean DEFAULT false NOT NULL,
	"dedicatedTime" real DEFAULT 0,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "flex-calendar_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flex-calendar_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "flex-calendar_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "flex-calendar_task_occurrence" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flex-calendar_task_occurrence_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"associatedTaskId" integer NOT NULL,
	"startDate" timestamp with time zone NOT NULL,
	"limitDate" timestamp with time zone,
	"targetDate" timestamp with time zone,
	"targetTimeConsumption" real,
	"timeConsumed" real DEFAULT 0,
	"status" varchar(50) DEFAULT 'Pending' NOT NULL,
	"urgency" real DEFAULT 0,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "flex-calendar_task_recurrence" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flex-calendar_task_recurrence_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"creationDate" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"interval" integer,
	"daysOfWeek" text[],
	"daysOfMonth" integer[],
	"maxOccurrences" integer,
	"completedOccurrences" integer DEFAULT 0,
	"lastPeriodStart" timestamp with time zone,
	"endDate" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "flex-calendar_task" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flex-calendar_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ownerId" varchar(255) NOT NULL,
	"name" varchar(512) NOT NULL,
	"description" text,
	"recurrenceId" integer,
	"importance" integer DEFAULT 5 NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "flex-calendar_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"password" varchar(255),
	CONSTRAINT "flex-calendar_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "flex-calendar_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "flex-calendar_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "flex-calendar_account" ADD CONSTRAINT "flex-calendar_account_userId_flex-calendar_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."flex-calendar_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flex-calendar_calendar_event" ADD CONSTRAINT "flex-calendar_calendar_event_ownerId_flex-calendar_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."flex-calendar_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flex-calendar_calendar_event" ADD CONSTRAINT "flex-calendar_calendar_event_associatedOccurrenceId_flex-calendar_task_occurrence_id_fk" FOREIGN KEY ("associatedOccurrenceId") REFERENCES "public"."flex-calendar_task_occurrence"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flex-calendar_post" ADD CONSTRAINT "flex-calendar_post_createdById_flex-calendar_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."flex-calendar_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flex-calendar_session" ADD CONSTRAINT "flex-calendar_session_userId_flex-calendar_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."flex-calendar_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flex-calendar_task_occurrence" ADD CONSTRAINT "flex-calendar_task_occurrence_associatedTaskId_flex-calendar_task_id_fk" FOREIGN KEY ("associatedTaskId") REFERENCES "public"."flex-calendar_task"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flex-calendar_task" ADD CONSTRAINT "flex-calendar_task_ownerId_flex-calendar_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."flex-calendar_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flex-calendar_task" ADD CONSTRAINT "flex-calendar_task_recurrenceId_flex-calendar_task_recurrence_id_fk" FOREIGN KEY ("recurrenceId") REFERENCES "public"."flex-calendar_task_recurrence"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "flex-calendar_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "event_owner_idx" ON "flex-calendar_calendar_event" USING btree ("ownerId");--> statement-breakpoint
CREATE INDEX "event_occurrence_idx" ON "flex-calendar_calendar_event" USING btree ("associatedOccurrenceId");--> statement-breakpoint
CREATE INDEX "event_start_idx" ON "flex-calendar_calendar_event" USING btree ("start");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "flex-calendar_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "flex-calendar_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "flex-calendar_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "occurrence_task_idx" ON "flex-calendar_task_occurrence" USING btree ("associatedTaskId");--> statement-breakpoint
CREATE INDEX "occurrence_status_idx" ON "flex-calendar_task_occurrence" USING btree ("status");--> statement-breakpoint
CREATE INDEX "occurrence_start_date_idx" ON "flex-calendar_task_occurrence" USING btree ("startDate");--> statement-breakpoint
CREATE INDEX "task_owner_idx" ON "flex-calendar_task" USING btree ("ownerId");--> statement-breakpoint
CREATE INDEX "task_recurrence_idx" ON "flex-calendar_task" USING btree ("recurrenceId");