CREATE TABLE "flex-calendar_notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flex-calendar_notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "flex-calendar_notification_user" (
	"notificationId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"readAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "flex-calendar_notification_user_notificationId_userId_pk" PRIMARY KEY("notificationId","userId")
);
--> statement-breakpoint
ALTER TABLE "flex-calendar_notification_user" ADD CONSTRAINT "flex-calendar_notification_user_notificationId_flex-calendar_notification_id_fk" FOREIGN KEY ("notificationId") REFERENCES "public"."flex-calendar_notification"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "flex-calendar_notification_user" ADD CONSTRAINT "flex-calendar_notification_user_userId_flex-calendar_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."flex-calendar_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "notification_active_idx" ON "flex-calendar_notification" USING btree ("isActive");--> statement-breakpoint
CREATE INDEX "notification_created_idx" ON "flex-calendar_notification" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "notification_user_notification_idx" ON "flex-calendar_notification_user" USING btree ("notificationId");--> statement-breakpoint
CREATE INDEX "notification_user_user_idx" ON "flex-calendar_notification_user" USING btree ("userId");